name: Build Aura-fit APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./aurafit

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.2'
          channel: stable

      - name: Generate missing Android project files
        run: flutter create --platforms=android .

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Flutter project
        run: flutter analyze || true

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aura-fit-apk
          path: aurafit/build/app/outputs/flutter-apk/app-release.apk
